dailyfresh/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('df_user.urls', namespace='df_user')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^', include('df_goods.urls', namespace='df_goods')),
    url(r'^cart/', include('df_cart.urls', namespace='df_cart')),
    url(r'^order/', include('df_order.urls', namespace='df_order')),
]

df_cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.cart, name='cart'),
    url(r'^add(\d+)_(\d+)/', views.add),
    url(r'^edit(\d+)_(\d+)/$', views.edit),
    url(r'^delete(\d+)/$', views.delete),
]

df_user/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^register_handle/$', views.register_handle, name='register_handle'),
    url(r'^login/$', views.login, name='login'),
    url(r'^login_handle/$', views.login_handle, name='login_handle'),
    url(r'^info/$', views.user_center_info, name='info'),
    url(r'^order_(\d+)/$', views.user_center_order, name='order'),
    url(r'^site/$', views.user_center_site, name='site'),
    url(r'^register_exist/$', views.register_exist, name='register_exist'),
    url(r'^logout/$', views.logout, name='logout'),

]

df_order/models.py
from django.db import models


class OrderInfo(models.Model):
    oid = models.CharField(max_length=20, primary_key=True)
    user = models.ForeignKey('df_user.UserInfo')
    odate = models.DateTimeField(auto_now=True)
    oIsPay = models.BooleanField(default=False)
    ototal = models.DecimalField(max_digits=8, decimal_places=2)
    oaddress = models.CharField(max_length=150)


class OrderDetailInfo(models.Model):
    goods = models.ForeignKey('df_goods.GoodsInfo')
    order = models.ForeignKey(OrderInfo)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    count = models.IntegerField()

df_user/models.py
from django.db import models


class UserInfo(models.Model):
    uname = models.CharField(max_length=20)
    upwd = models.CharField(max_length=40)
    uemail = models.CharField(max_length=40)
    addressee = models.CharField(max_length=20, default='')
    uaddress = models.CharField(max_length=100, default='')
    postcode = models.CharField(max_length=6, default='')
    uphone = models.CharField(max_length=11, default='')

df_user/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from .models import *
from . import user_decorator
from hashlib import sha1
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from df_goods.models import *
from df_order.models import *


def index(request):
    return redirect('/')


def register(request):
    return render(request, 'df_user/register.html', {'title': '天天生鲜-注册'})


def register_handle(request):
    # 接收用户输入
    post = request.POST
    uname = post.get('user_name')
    upwd = post.get('pwd')
    ucpwd = post.get('cpwd')
    uemail = post.get('email')
    count = UserInfo.objects.filter(uname=uname).count()
    # 判断两次密码
    if upwd != ucpwd:
        return redirect('/user/register/')
    elif count != 0:
        return redirect('/user/register/')
    # 密码加密
    s1 = sha1()
    s1.update(upwd.encode('utf-8'))
    upwd2 = s1.hexdigest()
    # 创建对象
    user = UserInfo()
    user.uname = uname
    user.upwd = upwd2
    user.uemail = uemail
    user.save()
    # 注册成功, 转到登录页面
    return redirect('/user/login/')


def register_exist(request):
    uname = request.GET.get('uname')
    count = UserInfo.objects.filter(uname=uname).count()
    return JsonResponse({'count': count})


def login(request):
    uname = request.COOKIES.get('uname', '')
    context = {'title': '天天生鲜-登录', 'error_name': 0, 'error_pwd': 0, 'uname': uname}
    return render(request, 'df_user/login.html', context)


def login_handle(request):
    post = request.POST
    uname = post.get('username')
    upwd = post.get('pwd')
    remember = post.get('remember', 0)
    users = UserInfo.objects.filter(uname=uname)
    if len(users) == 1:
        s1 = sha1()
        s1.update(upwd.encode('utf-8'))
        if s1.hexdigest() == users[0].upwd:
            url = request.COOKIES.get('url', '/')
            red = HttpResponseRedirect(url)
            # if remember != 0:
            #     red.set_cookie('uname', uname)
            # else:
            #     red.set_cookie('uname','', max_age=-1)
            request.session['user_id'] = users[0].id
            request.session['user_name'] = uname
            return red
        else:
            if remember == 0:
                uname = ''
            context = {'title': '天天生鲜-登录', 'error_name': 0, 'error_pwd': 1, 'uname': uname}
            return render(request, 'df_user/login.html', context)
    else:
        if remember == 0:
            uname = ''
        context = {'title': '天天生鲜-登录', 'error_name': 1, 'error_pwd': 0, 'uname': uname}
        return render(request, 'df_user/login.html', context)


def logout(request):
    request.session.flush()
    return redirect('/')


@user_decorator.login
def user_center_info(request):
    id = request.session['user_id']
    user = UserInfo.objects.get(pk=id)
    goods_ids = request.COOKIES.get('goods_ids', '')
    goods_ids1 = goods_ids.split(',')
    goods_list = []
    for goods_id in goods_ids1:
        if goods_id != '':
            goods_list.append(GoodsInfo.objects.get(pk=int(goods_id)))

    context = {'title': '天天生鲜-用户中心', 'user': user, 'goods_list': goods_list}
    return render(request, 'df_user/user_center_info.html', context)



@user_decorator.login
def user_center_order(request, pindex):
    id = request.session['user_id']
    user = UserInfo.objects.get(pk=id)
    orders = OrderInfo.objects.filter(user_id=id).order_by('oIsPay', '-oid')
    paginator = Paginator(orders, 2)
    page = paginator.page(int(pindex))
    context = {'title': '天天生鲜-用户中心', 'user': user, 'orders': orders, 'paginator': paginator, 'page': page}
    return render(request, 'df_user/user_center_order.html', context)


@user_decorator.login
def user_center_site(request):
    id = request.session['user_id']
    user = UserInfo.objects.get(pk=id)
    if request.method == 'POST':
        post = request.POST
        addressee = post.get('addressee')
        uaddress = post.get('uaddress')
        postcode = post.get('postcode')
        uphone = post.get('phone')
        user.addressee = addressee
        user.uaddress = uaddress
        user.postcode = postcode
        user.uphone = uphone
        user.save()
    context = {'title': '天天生鲜-用户中心', 'user': user}
    return render(request, 'df_user/user_center_site.html', context)



templates/df_user/base.html
{% extends 'base_foot.html' %}
{% load staticfiles %}
{% load static from staticfiles %}
{% block body %}
<div class="header_con">
    <div class="header">
        <div class="welcome fl">此页面仅用作测试,如有侵权请联系删除!</div>
        <div class="fr">
            {% if request.session.user_name|default:'' != '' %}
            <div class="login_info fl">
                欢迎您：<em>{{request.session.user_name}}</em>
                <span>|</span>
                <a href="{% url 'df_user:logout' %}">退出</a>
            </div>
            {% else %}
            <div class="login_btn fl">
                <a href="{% url 'df_user:login' %}">登录</a>
                <span>|</span>
                <a href="{% url 'df_user:register' %}">注册</a>
            </div>
            {% endif %}
            <div class="user_link fl">
                <span>|</span>
                <a href="{% url 'df_user:info' %}">用户中心</a>
                <span>|</span>
                <a href="{% url 'df_cart:cart' %}">我的购物车</a>
                <span>|</span>
                <a href="{% url 'df_user:order' 1 %}">我的订单</a>
            </div>
        </div>
    </div>
</div>
<div class="search_bar clearfix">
	<a href="{%url 'df_goods:index'%}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
	<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
	<div class="search_con fr">
		<input type="text" class="input_text fl" name="" placeholder="搜索商品">
		<input type="button" class="input_btn fr" name="" value="搜索">
	</div>
    <!--<div class="guest_cart fr">-->
			<!--<a href="#" class="cart_name fl">我的购物车</a>-->
			<!--<div class="goods_count fl" id="show_count">1</div>-->
		<!--</div>-->
</div>

{% block body2%}{% endblock body2%}


{% endblock body %}

templates/df_user/login.html
{% extends 'base_foot.html' %}
{% load static from staticfiles %}
{% block body %}
	<div class="login_top clearfix">
		<a href="{%url 'df_goods:index'%}" class="login_logo"><img src="{% static 'images/logo02.png' %}"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'df_user:register' %}">立即注册</a>
				</div>
				<div class="form_input">
					<form action="{% url 'df_user:login_handle' %}" method="post">
                        {% csrf_token %}
						<input type="text" name="username" class="name_input" value="{{uname}}" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="remember" value="1" checked="checked">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="button" name="" value="登录" class="input_submit" id="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>

{% block newjs %}
<script type="text/javascript">
    $(function () {
        var name_error = false;
        var pwd_error = false;
        if({{error_name}}==1){
            $('.user_error').html('用户名错误').show();
        };
        if({{error_pwd}}==1){
            $('.pwd_error').html('密码错误').show();
        };
        $('.name_input').blur(function () {
            check_user_name();
        });
        $('.pass_input').blur(function () {
            check_pwd();
        });
        function check_user_name() {
            if($('.name_input').val().length==0){
                $('.user_error').html('请输入用户名').show();
                name_error=true;
            }else {
                $('.user_error').hide();
                name_error=false;
            }
        };
        function check_pwd() {
            if($('.pass_input').val().length==0){
                $('.pwd_error').html('请输入密码').show();
                name_error=true;
            }else {
                $('.pwd_error').hide();
                name_error=false;
            }
        };
        $('#input_submit').click(function () {
            check_user_name();
            check_pwd();
            if(name_error==false && pwd_error==false){
                $(this).prop("type","submit");
                return true
            }else {
                return false
            };
        });
    });

</script>
{% endblock newjs %}



{% endblock body %}

templates/df_user/register.html
{% extends 'base_foot.html' %}
{% load staticfiles %}
<!--{% load static from staticfiles %}-->
{%block head%}<script type="text/javascript" src="{% static 'js/register.js' %}"></script>{%endblock head%}

{% block body %}
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo" href="{%url 'df_goods:index'%}"><img src="{% static 'images/logo02.png' %}"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="{% url 'df_user:login' %}">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form action="{% url 'df_user:register_handle' %}" method="post">
                    {% csrf_token %}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>					
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="button" value="注 册" id="go_sub">
					</li>
				</ul>				
				</form>
			</div>

		</div>

	</div>
{% endblock body %}

templates/df_user/user_center_info.html
{% extends 'df_user/base.html' %}
{% load staticfiles %}
{% load static from staticfiles %}
{% block body2%}

<div class="main_con clearfix">
	<div class="left_menu_con clearfix">
		<h3>用户中心</h3>
		<ul>
			<li><a href="{% url 'df_user:info' %}" class="active">· 个人信息</a></li>
			<li><a href="{% url 'df_user:order' 1 %}">· 全部订单</a></li>
			<li><a href="{% url 'df_user:site' %}">· 收货地址</a></li>
		</ul>
	</div>
	<div class="right_content clearfix">
			<div class="info_con clearfix">
			<h3 class="common_title2">基本信息</h3>
					<ul class="user_info_list">
						<li><span>用户名：</span>{{user.uname}}</li>
						<li><span>联系方式：</span>{{user.uphone}}</li>
						<li><span>联系邮箱：</span>{{user.uemail}}</li>
					</ul>
			</div>

			<h3 class="common_title2">最近浏览</h3>
			<div class="has_view_list">
				<ul class="goods_type_list clearfix">
					{%for goods in goods_list%}
					<li>
						<a href="/{{goods.gid}}/"><img src="/static/{{goods.gpic}}"></a>
						<h4><a href="/{{goods.gid}}/">{{goods.gtitle}}</a></h4>
						<div class="operate">
							<span class="prize">￥{{goods.gprice}}</span>
							<span class="unit">{{goods.gprice}}/{{goods.gunit}}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
						</div>
					</li>
					{%endfor%}
		    </ul>
	    </div>
	</div>
</div>
{% endblock body2%}

{% block newjs %}
<script type="text/javascript">
    $(function () {
        $('.login_info').show();
        // $('.guest_cart').hide();
    });
</script>
{% endblock newjs %}

templates/df_user/user_center_order.html
{% extends 'df_user/base.html' %}
{% load staticfiles %}
{% load static from staticfiles %}
{% block body2%}

<div class="main_con clearfix">
    <div class="left_menu_con clearfix">
        <h3>用户中心</h3>
        <ul>
            <li><a href="{% url 'df_user:info' %}">· 个人信息</a></li>
            <li><a href="{% url 'df_user:order' 1 %}" class="active">· 全部订单</a></li>
            <li><a href="{% url 'df_user:site' %}">· 收货地址</a></li>
        </ul>
    </div>
    <div class="right_content clearfix">
        <h3 class="common_title2">全部订单</h3>
        {% for order in orders %}
        <ul class="order_list_th w978 clearfix">
            <li class="col01">{{order.odate}}</li>
            <li class="col02">订单号：{{order.oid}}</li>
            {% if order.oIsPay == true %}
            <li class="col02 stress">已支付</li>
            {% else %}
            <li class="col02 stress">未支付</li>
            {% endif %}
        </ul>

        <table class="order_list_table w980">
            <tbody>
                <tr>
                    <td width="55%">
                        {% for item in order.orderdetailinfo_set.all %}
                        <ul class="order_goods_list clearfix">
                            <li class="col01"><img src="/static/{{item.goods.gpic}}"></li>
                            <li class="col02">{{item.goods.gtitle}}<em>单价: {{item.price}}元/{{item.goods.gunit}}</em></li>
                            <li class="col03">数量: {{item.count}}</li>
                            <li class="col04"></li>
                        </ul>
                        {% endfor %}

                    </td>
                    <td width="15%">{{order.ototal}}元</td>
                    {% if order.oIsPay == true%}
                    <td width="15%">已付款</td>
                    <td width="15%"><a href="#" class="oper_btn">查看物流</a></td>
                    {% else %}
                    <td width="15%">未付款</td>
                    <td width="15%"><a href="#" class="oper_btn">去付款</a></td>
                    {% endif %}
                </tr>
            </tbody>
        </table>
        {% endfor %}


        <div class="pagenation">
            {%if page.has_previous%}
			<a href="/user/order_{{page.previous_page_number}}">上一页</a>
            {%endif%}

            {%for index in paginator.page_range%}
            {%if index == page.number%}
			<a href="#" class="active">{{index}}</a>
            {%else%}
			<a href="/user/order_{{index}}">{{index}}</a>
            {%endif%}
			{%endfor%}

            {%if page.has_next%}
			<a href="/user/order_{{page.next_page_number}}">下一页</a>
            {%endif%}
        </div>
    </div>
</div>

{% endblock body2%}

{% block newjs %}
<script type="text/javascript">
    $(function () {
        $('.login_info').show();
        // $('.guest_cart').hide();
    });
</script>
{% endblock newjs %}

templates/df_user/user_center_site.html
{% extends 'df_user/base.html' %}
{% load staticfiles %}
{% load static from staticfiles %}
{% block body2%}

<div class="main_con clearfix">
	<div class="left_menu_con clearfix">
		<h3>用户中心</h3>
		<ul>
			<li><a href="{% url 'df_user:info' %}">· 个人信息</a></li>
			<li><a href="{% url 'df_user:order' 1 %}">· 全部订单</a></li>
			<li><a href="{% url 'df_user:site' %}" class="active">· 收货地址</a></li>
		</ul>
	</div>
	<div class="right_content clearfix">
			<h3 class="common_title2">收货地址</h3>
			<div class="site_con">
				<dl>
					<dt>当前地址：</dt>
					<dd>{{user.uaddress}} （{{user.addressee}} 收） {{user.uphone}}</dd>
				</dl>
			</div>
			<h3 class="common_title2">编辑地址</h3>
			<div class="site_con">
				<form action="{% url 'df_user:site' %}" method="post">
					{% csrf_token %}
					<div class="form_group">
						<label>收件人：</label>
						<input type="text" name="addressee">
					</div>
					<div class="form_group form_group2">
						<label>详细地址：</label>
						<textarea class="site_area" name="uaddress"></textarea>
					</div>
					<div class="form_group">
						<label>邮编：</label>
						<input type="text" name="postcode">
					</div>
					<div class="form_group">
						<label>手机：</label>
						<input type="text" name="phone">
					</div>

					<input type="submit" name="" value="提交" class="info_submit">
				</form>
			</div>
	</div>
</div>

{% endblock body2%}

{% block newjs %}
<script type="text/javascript">
    $(function () {
        $('.login_info').show();
        // $('.guest_cart').hide();
    });
</script>
{% endblock newjs %}